name: import-options
on: push
jobs:
  import-options:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Import JSON into database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm start
# TODO: Run a build script to create the "Default" release pack
#on:
#  push:
#    tags:
#    - 'v*'
#jobs:
#  build-default:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          draft: true
#          prerelease: true
#      - name: Upload Release Asset
#        id: upload-release-asset
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: build/combined.json
#          asset_name: combined.json
#          asset_content_type: application/json